/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtons: typeof import('./src/components/wine/ActionButtons.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BaseWineForm: typeof import('./src/components/wine/BaseWineForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CountryForm: typeof import('./src/components/country/CountryForm.vue')['default']
    CountryTable: typeof import('./src/components/country/CountryTable.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FilterSection: typeof import('./src/components/wine/FilterSection.vue')['default']
    FilterSelect: typeof import('./src/components/wine/FilterSelect.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    ForgotPasswordDialog: typeof import('./src/components/ForgotPasswordDialog.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/form/ForgotPasswordForm.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    GrapeForm: typeof import('./src/components/grape/GrapeForm.vue')['default']
    GrapeTable: typeof import('./src/components/grape/GrapeTable.vue')['default']
    HeaderSection: typeof import('./src/components/wine/HeaderSection.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RegionForm: typeof import('./src/components/region/RegionForm.vue')['default']
    RegionTable: typeof import('./src/components/region/RegionTable.vue')['default']
    ResetPasswordForm: typeof import('./src/components/form/ResetPasswordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Slider: typeof import('primevue/slider')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    WineDetailsDialog: typeof import('./src/components/wine/WineDetailsDialog.vue')['default']
    WineDialog: typeof import('./src/components/wine/WineDialog.vue')['default']
    WineEditDialog: typeof import('./src/components/wine/WineEditDialog.vue')['default']
    WineEditImageDialog: typeof import('./src/components/wine/WineEditImageDialog.vue')['default']
    WineSearchDialog: typeof import('./src/components/wine/WineSearchDialog.vue')['default']
    WineTable: typeof import('./src/components/wine/WineTable.vue')['default']
  }
  export interface ComponentCustomProperties {
    KeyFilter: typeof import('primevue/keyfilter')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
